name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          #node-version: 20.18.1
#          node-version: 12

#      - name: Install dependencies
#        run: npm install
#        working-directory: telon-gateway-app
#
#      - name: Run tests
#        run: npm test

  build_android:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      #- name: Setup Java 8
      #  uses: actions/setup-java@v2
      #  with:
      #    distribution: 'temurin'
      #    java-version: '8' # Требуется Java 8 для Gradle

      - name: Cache Node.js
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Set up OpenJDK 8
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk

      - name: Setup Android SDK (API Level 19)
        # android-actions has v3.x releases — v4 doesn't exist, поэтому переключаемся на @v3.
        uses: android-actions/setup-android@v3
        with:
          api-level: 19
          ndk: true
          build-tools: 25.2.5
      #    build-tools: 30.0.3

      - name: Download NDK r17b
        run: |
          curl -o android-ndk-r17b-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
          unzip android-ndk-r17b-linux-x86_64.zip -d $HOME/android-ndk
          rm android-ndk-r17b-linux-x86_64.zip

      - name: Set NDK path
        run: |
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ndk.dir=$HOME/android-ndk/android-ndk-r17b" > $GITHUB_WORKSPACE/local.properties

      - name: Verify NDK installation
        run: |
          echo "NDK_HOME=$NDK_HOME"
          ls -la $NDK_HOME

      - name: Install Dependencies
        run: npm install
        working-directory: telon-gateway-app

      - name: Build Android App Bundle
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew 
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app

  download_bundle:
    runs-on: ubuntu-latest

    needs: build_android

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Download Android App Bundle
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist
          # Исправленный путь: сборка находится в telon-gateway-app/android/...
          cp $GITHUB_WORKSPACE/telon-gateway-app/android/app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/dist
        working-directory: telon-gateway-app

      - name: Archive Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: $GITHUB_WORKSPACE/dist
